
public class Exception2 {

	public static void main(String[] args) {
		int num=10;
		int a=0;
		try
		{
			System.out.println(num/a);				
		}
		catch(Exception aie)
		{
			System.out.println(aie);
		}
		
	}

}
